# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(default=b'2018-10-17')),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('CP', 'Completed')], default='PD', max_length=2)),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
    ]
