# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='delete_time',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todoapp.Task'),
        ),
        migrations.AddField(
            model_name='task',
            name='soft_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
