# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-20 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_auto_20181019_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=b'2018-10-20'),
        ),
    ]
